function Y_bar=preprocess_proposed(Y,Fs,threshold,f_buttord)
[L,~]=size(Y);
baseline = cos(2*pi*60*(0:L-1)/Fs);
Y=Y.*baseline.';
Y=hilbert(Y);
Y=abs(Y);
Y=hilbert(Y);
Y = Y - mean(Y);
Y=Butterworth(Y,f_buttord(1),f_buttord(2));
%%
I=eye(L/2);
J=flip(I);
Q=[I,J;1j*J,-1j*I]/sqrt(2);
bar_Y=Q*Y;
bar_Y_R=real(bar_Y);
bar_Y_I=imag(bar_Y);
tilde_Y=[bar_Y_R,bar_Y_I];
[~,S,V] = svd(tilde_Y);
s=diag(S);
V=V(:,s>max(s)*threshold);
Y_bar=tilde_Y*V;
Y_bar=Y_bar-mean(Y_bar);